[package]
name = "storage-order-meta"
version = "0.0.1"
edition = "2018"
publish = false
authors = [ "yaoz",]

[dev-dependencies]

[dependencies.storage-order]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.29.3"
